server:
  port: 80
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: cilent-feign   #自定义服务名称信息
#开启hystrix降级
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: client-80
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8