spring:
  profiles:
   active: dev
---
spring:
  profiles: dev
  application:
    name: springcloud-config-dev
server:
 port: 8201
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8002   #自定义服务名称信息

---
spring:
  profiles: test
  application:
    name: springcloud-config-test
server:
 port: 8202
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8002   #自定义服务名称信息