server:
  port: 9527
spring:
  application:
    name: springcloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    #设置路由
    myEployee.serviceId: client-80
    myEployee.path: /train/**
  #隐藏原本的路径，"*"隐藏所有微服务路径
  ignored-services: client-80
  #设置访问前缀
  prefix: /hand
